services:
  - type: web
    name: video-overlay-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TEMP_DIR
        value: /tmp
      - key: OUTPUT_DIR
        value: /tmp
      - key: FFMPEG_PATH
        value: ffmpeg
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health
